/**
 * PrismCodeBlock React Component
 * Wrapper component for rendering Prism.js highlighted code blocks
 * Works with HTML generated by V2CodeNormalizationSystem backend
 */

import React, { useEffect, useRef } from 'react';
import prismManager from '../utils/prismSetup';

const PrismCodeBlock = ({ 
  children, 
  className = '', 
  onHighlight = null 
}) => {
  const containerRef = useRef(null);

  useEffect(() => {
    if (containerRef.current) {
      // Highlight code blocks in this container
      prismManager.highlightAllUnder(containerRef.current);
      
      // Call optional callback
      if (onHighlight) {
        onHighlight();
      }
    }
  }, [children, onHighlight]);

  return (
    <div 
      ref={containerRef}
      className={`prism-container ${className}`}
      dangerouslySetInnerHTML={{ __html: children }}
    />
  );
};

/**
 * HTMLContent Component
 * Safely renders HTML content with Prism highlighting and markdown link processing
 * Ideal for content from V2 Engine that contains code blocks and Mini-TOC links
 */
const HTMLContent = ({ 
  html, 
  className = '', 
  onRender = null 
}) => {
  const contentRef = useRef(null);

  const processMarkdownLinks = (content) => {
    // Convert markdown-style anchor links [text](#anchor) to HTML links
    return content.replace(/\[([^\]]+)\]\(#([^)]+)\)/g, '<a href="#$2" class="toc-link text-blue-600 hover:text-blue-800 hover:underline">$1</a>');
  };

  const convertH1ToH2 = (content) => {
    // TICKET 1 FIX: Convert any H1 elements in content to H2 to prevent title duplication
    // This ensures only the UI title appears as H1, while content starts with H2
    return content.replace(/<h1(\s[^>]*)?>/gi, '<h2$1>').replace(/<\/h1>/gi, '</h2>');
  };

  const addSmoothScrolling = (container) => {
    // Add click handlers for anchor links to enable smooth scrolling
    const anchorLinks = container.querySelectorAll('a[href^="#"]');
    anchorLinks.forEach(link => {
      link.addEventListener('click', (e) => {
        e.preventDefault();
        const targetId = link.getAttribute('href').substring(1);
        const targetElement = document.getElementById(targetId);
        
        if (targetElement) {
          targetElement.scrollIntoView({
            behavior: 'smooth',
            block: 'start'
          });
          
          // Add temporary highlight to target heading
          targetElement.style.transition = 'background-color 0.3s ease';
          targetElement.style.backgroundColor = '#fef3c7';
          setTimeout(() => {
            targetElement.style.backgroundColor = '';
          }, 2000);
        }
      });
    });
  };

  useEffect(() => {
    if (contentRef.current && html) {
      // Process markdown links first
      const processedHtml = processMarkdownLinks(html);
      
      // Set the processed HTML content
      contentRef.current.innerHTML = processedHtml;
      
      // Add smooth scrolling to anchor links
      addSmoothScrolling(contentRef.current);
      
      // Highlight any code blocks
      prismManager.highlightAllUnder(contentRef.current);
      
      // Call optional callback
      if (onRender) {
        onRender(contentRef.current);
      }
    }
  }, [html, onRender]);

  return (
    <div 
      ref={contentRef}
      className={`html-content ${className}`}
    />
  );
};

/**
 * StaticCodeBlock Component  
 * For rendering individual code blocks with known language using simplified markup
 */
const StaticCodeBlock = ({ 
  code, 
  language = 'text',
  showLineNumbers = true,
  filename = null,
  caption = null,
  className = ''
}) => {
  const codeRef = useRef(null);

  useEffect(() => {
    if (codeRef.current) {
      prismManager.highlightElement(codeRef.current);
    }
  }, [code, language]);

  const languageClass = `language-${language}`;
  const preClass = showLineNumbers ? 'line-numbers' : '';
  
  // Build data attributes
  const dataAttrs = {
    'data-lang': language.toUpperCase(),
    'data-start': '1'
  };
  if (filename) {
    dataAttrs['data-filename'] = filename;
  }

  return (
    <div className={className}>
      <pre className={preClass} {...dataAttrs}>
        <code 
          ref={codeRef}
          className={languageClass}
        >
          {code}
        </code>
      </pre>
      {caption && (
        <p className="code-caption"><em>{caption}</em></p>
      )}
    </div>
  );
};

/**
 * CodeHighlighter Hook
 * Custom hook for manual highlighting control
 */
const useCodeHighlighter = () => {
  const highlightAll = () => {
    prismManager.highlightAll();
  };

  const highlightContainer = (container) => {
    if (container) {
      prismManager.highlightAllUnder(container);
    }
  };

  const highlightElement = (element) => {
    if (element) {
      prismManager.highlightElement(element);
    }
  };

  return {
    highlightAll,
    highlightContainer,
    highlightElement,
    reinitialize: prismManager.reinitialize.bind(prismManager)
  };
};

export default PrismCodeBlock;
export { HTMLContent, StaticCodeBlock, useCodeHighlighter };